### ISSUE TITLE
[=BUG=] Cannot fetch tracks from SpotifyAlbum or SpotifyPlaylist

### ISSUE THREAD

**Issue by Maksim-Lipenka** [play-dl/play-dl#110]
#### Describe the bug

I'm trying to .fetch() tracks from SpotifyAlbum/Playlist but get undefined

 - Node.js version: 16.9.1
 - OS & version: Windows 10

#### Actual behavior
get album with play.spotify() --> get tracks from album with .fetch --> success

#### Expected behavior
get album with play.spotify() --> get tracks from album with .fetch --> got undefined
 

#### Code to reproduce

```js
if (
      /^(ftp|http|https):\/\/[^ "]+$/.test(query) &&
      playDl.sp_validate(query)
    ) {
      if (playDl.is_expired()) {
        await playDl.refreshToken()
      }
      playDl
        .spotify(query)
        .then(async (data) => {
          switch (data.type) {
            case 'album':
              const test = await data.fetch()
              console.log(data) // I can see fetched_tracks private property with correct data, but no result with .fetch()
              console.log(test) // undefined
              break
            default:
              break
          }
        })
        .catch((error) => {
          console.error(error) // no error
        })
    }
```

#### Checklist
I see fetched_tracks when log album response from play.spotify() but this property is private
![image](https://user-images.githubusercontent.com/43496357/134783570-654f066b-a464-4845-afb1-1df266482e42.png)

- [yes] I have read the documentation.
- [yes] I have tried my code with the latest version of Node.js and Play-dl.

Am I doing something wrong?

**Comment by MahoMuri** [comment]
owo it's not a bug hehe I've asked this same question! 

Please refer [here](https://github.com/play-dl/play-dl/discussions/78) for the author's answer :>

**Comment by Maksim-Lipenka** [comment]
@MahoMuri ah, I see, it fetches data to SpotifyAlbum instance, not return, thank you!!
