### ISSUE TITLE
[=BUG=] YouTube Extract ID not respecting YouTube ID format

### ISSUE THREAD

**Issue by PapiOphidian** [play-dl/play-dl#117]
#### Describe the bug

 - Node.js version: 16.6
 - OS & version: Ubuntu 20

YouTube's extractID fn doesn't check for if the extracted ID matches the /^[a-zA-Z\d]+$/ (Video IDs only. PL includes - and \d)

#### Actual behavior
The extractor can return IDs which include any characters.

#### Expected behavior
The extractor throws an Error expecting the ID to be in a specific format

#### Code to reproduce

```js
const play = require("play-dl")
const testString = "pogu my guy$$XD";
const val = play.extractID(testString);
console.log(testString === val); // true
```

#### ScreenShots
N.A.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
> YouTube's extractID fn doesn't check for if the extracted ID matches the /^[a-zA-Z]+$/ (Video IDs only. PL includes - and \d)

That is a invalid regexp for video ID. I will include in next update.

**Comment by PapiOphidian** [comment]
Accidentally forgot that video IDs can include \d

**Comment by killer069** [comment]
Yup numbers are also there

**Comment by PapiOphidian** [comment]
Updated regex

**Comment by killer069** [comment]
> Updated regex

One more thing, video ID is only 11 character long. So add `{11}` also.

**Comment by PapiOphidian** [comment]
The IDs may spill over that amount of characters at some point, so I always advise against specifying ID lengths

**Comment by killer069** [comment]
@PapiOphidian

Regexp is still wrong.
