### ISSUE TITLE
[=BUG=] Handeling of legacy format videos

### ISSUE THREAD

**Issue by absidue** [play-dl/play-dl#122]
#### Describe the bug

 - Node.js version: 16.11.0
 - OS & version: Windows 10
 - play-dl version: 1.0.8

When trying to stream a video with only legacy formats available (video and audio merged into mp4), play-dl tries to read the `codec` property of `undefined`.

The video in question only provides a 360p mp4 stream: [https://youtube.com/watch?v=aA6zYJNPWXI](https://youtube.com/watch?v=aA6zYJNPWXI)

#### Actual behavior

```
Uncaught TypeError: Cannot read properties of undefined (reading 'codec')
    at Object.stream (C:\workspace\boombox_bot\node_modules\.pnpm\play-dl@1.0.8\node_modules\play-dl\dist\YouTube\stream.js:54:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async stream (C:\workspace\boombox_bot\node_modules\.pnpm\play-dl@1.0.8\node_modules\play-dl\dist\index.js:49:16)
```

#### Expected behavior

Ideally play-dl would handle legacy format videos by piping the stream to ffmpeg to convert to opus, it might have a noticable performance impact depending on the host machine. Alternatively play-dl could throw an error stating that the video doesn't provide a format that play-dl is capable of dealing with, that way each developer could decide for themselves how they want to handle such cases.

#### Code to reproduce

```js
const { stream } = require('play-dl');

(async function() {
    await stream('aA6zYJNPWXI');
})();
```

#### ScreenShots

See console output in the Actual behavior section

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
Thanks for reporting. This will be fixed in next update.
