### ISSUE TITLE
[=BUG=] MaxListenersExceededWarning in PassThrough

### ISSUE THREAD

**Issue by Eralyne** [play-dl/play-dl#125]
#### Describe the bug

 - Node.js version: 16.9.1
 - OS & version: Raspbian 10

```
(node:620) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(node:620) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(node:620) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(node:620) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(node:620) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
```

This seems to be similar to the issue that was "fixed" and discussed here: https://github.com/play-dl/play-dl/issues/52

The only difference that I am seeing is that this time it includes "drain listeners" whereas the previous one did not include that remark. 

For further information, I am using a proxy to run the stream.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
Please also send the url that created this issue.

**Comment by Eralyne** [comment]
Checking the logs, this video was being played when the issue came up: https://www.youtube.com/watch?v=VGijVRLc7W4

Additionally, unlike the previous issue, this only occurred once in the stream going through from the error to drain and stopping. This song was, however, looped a lot (46 times). 

The same issue appeared with this track https://www.youtube.com/watch?v=_BaKgJcv9MA after about 16-20 or so minutes into the song when I was testing the proxy with it. I do not fully remember the timestamp. The memory leak error appeared only in one batch as well, with the same results.
