### ISSUE TITLE
[=BUG=] Cannot read property split of undefined when extracting youtu.be url ID.

### ISSUE THREAD

**Issue by PapiOphidian** [play-dl/play-dl#129]
#### Describe the bug

 - Node.js version: 16.0.0
 - OS & version: Windows 11

```
> const yt = require("play-dl");
undefined
> yt.extractID("https://youtu.be/nBcTKyqwlcI");
Uncaught TypeError: Cannot read property 'split' of undefined
    at yt_validate (C:\Users\papi\Documents\GitHub\Volcano\node_modules\play-dl\dist\YouTube\utils\extractor.js:22:46)
    at Object.extractID (C:\Users\papi\Documents\GitHub\Volcano\node_modules\play-dl\dist\YouTube\utils\extractor.js:58:19)
```

#### Actual behavior
The function errors

#### Expected behavior
The ID gets extracted properly

#### Code to reproduce
Refer to console output for code used

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
This is know bug, will be fixed in next update.
