### ISSUE TITLE
[=BUG=] Initial Player Response Data is undefined (possibly proxy)

### ISSUE THREAD

**Issue by Eralyne** [play-dl/play-dl#147]
#### Describe the bug

Some songs throw this error. I personally have not been able to reproduce it but my users see it, especially after songs play for a while on the same proxy. Strangely, when it occurs it only happens on one song and others work fine.

The songs that the issue has been noticed on have been (the Spotify one is converted to the VEVO youtube version of it):
https://www.youtube.com/watch?v=B4MOVJg6WbI
https://open.spotify.com/track/2gbMPBrBVj3CuNTLp2dHYs?si=7cb55bff04a84da1

 - Node.js version: 16.9.1
 - OS & version: Raspbian 10

#### Actual behavior

Certain songs throw the error listed in the title.

#### Expected behavior

All songs should play normally.

#### ScreenShots

![Screenshot 2021-10-29 161031](https://user-images.githubusercontent.com/7963271/139562581-4d238768-f3fc-4ddb-8bca-ef2937f3a0b1.png)

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by Jettucis** [comment]
These links are working fine for me, I think that there's something with your code.
Could you post your code where you use play-dl here please?

**Comment by killer069** [comment]
Jettucis is correct. Give us a working code so that we can experience same thing.

**Comment by Eralyne** [comment]
As I mentioned, I have personally not been able to reproduce it. It seems to occur after songs play for *a while*. My code is merely creating a stream from the URL; that is the only instance of play-dl that I use.

`await playdl.stream(track, { proxy: proxies })).stream`

`track` is a URL.

**Comment by Eralyne** [comment]
I cannot trace what causes the issue on my end. When creating a stream from video info, the problem occurs on both video_info retrieval and creating the stream from video info. The same song can throw this issue and then work perfectly fine when resetting the stream. **It looks like it occurs more often when using video info**

I have tested, my URL is unchanged between when it works and does not work. 
This is a recent problem since the proxy update and has not occurred prior (albeit I was told that error handling was implemented so this error may have been disguised as something unhandled prior). My end has had no code changes.

**Comment by Gary50613** [comment]
this happends to me today, and I saw a lot of this error happened when I try to use `video_basic_info` function.
even if I tried to use `htmldata`, it still happen.

`play-dl@1.8.6`

![image](https://user-images.githubusercontent.com/33802653/153122186-58dbbb1d-cca5-4873-9368-8312dada3922.png)
