### ISSUE TITLE
[=BUG=] validate() and yt_validate() returning a false promise even with a valid playlist link.

### ISSUE THREAD

**Issue by Fadhli890** [play-dl/play-dl#148]
#### Describe the bug

 - Node.js version: 16.9.1
 - OS & version: Windows 10

The `validate()` and `yt_validate()` function returns a `Promise<false> | false` even when it's provided with a valid playlist [link](https://www.youtube.com/playlist?list=OLAK5uy_mQpLBz0N6mCebSVw7xfyf_x7UZKoVHm_Q).

#### Actual behavior
Return a false promise even with a valid link.

#### Expected behavior
Should returned a `yt_playlist` type.

#### Code to reproduce

```ts
import Command from "../structures/Command";
import { validate } from 'play-dl'

export default new Command({
	name: "test",
	description: "test",
	async execute(message, args) {
		const val = await validate(args[0])
		console.log(args[0])
		console.log(val)
	}
})
```

#### ScreenShots
![image](https://user-images.githubusercontent.com/67270658/139580239-ee0e3511-e3b6-4601-9413-261206fac3ea.png)

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by Jettucis** [comment]
It returns false because the pattern of the playlist url is non-compatible with play-dl.
In your example url has ?list=**O**L, but validate function validates ?list=**P**L.

It's intentional.

**Comment by killer069** [comment]
Can you tell if this is a youtube generated playlist or user generated ??

**Comment by absidue** [comment]
@Jettucis AFAIK only the ones starting with RD are auto generated mixes

**Comment by Fadhli890** [comment]
@Jettucis I see, thank you for the respond. does this have a possibility of being implemented in the future?

**Comment by killer069** [comment]
@Fadhli890 

Provide that playlist url. I want to check something.

**Comment by Fadhli890** [comment]
@killer069 https://www.youtube.com/playlist?list=OLAK5uy_mQpLBz0N6mCebSVw7xfyf_x7UZKoVHm_Q
