### ISSUE TITLE
[=BUG=] Unavailable video breaks playlist_info(url)

### ISSUE THREAD

**Issue by Junhaochia** [play-dl/play-dl#15]
#### Describe the bug

 - Node.js version: 16.7.0
 - OS & version: linux (most likely latest)

playlist_info throws an TypeError when there is unavailable video that is hidden instead of returning the rest of the playlist.

#### Actual behavior
It Throws an TypeError as response.alerts[0] does not contain attribute alertRenderer:

Output of `console.log(JSON.stringify(response.alerts));`
```js
[{"alertWithButtonRenderer":{"type":"INFO","text":{"simpleText":"1 unavailable video is hidden"},"dismissButton":{"buttonRenderer":{"style":"STYLE_DEFAULT","size":"SIZE_DEFAULT","isDisabled":false,"icon":{"iconType":"CLOSE"},"trackingParams":"CCQQ8FsiEwizpMKrq8fyAhUNplEKHV-iDng=","accessibilityData":{"accessibilityData":{"label":"Dismiss"}}}}}}]
```

#### Expected behavior

It should just ignore the unavailable video, and process the playlist.

#### Code to reproduce
URL where a playlist contains a video that is not available for the server host's country ( mostly likely due to region lock). 
```js
const res = await (await playlist_info(url)).fetch();
```

#### Screenshots
![image](https://user-images.githubusercontent.com/25685501/130464496-d91a30d3-2aa5-4cb3-b41b-f7297938e323.png)

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Play-dl.

### How I temporary fixed it on my end.
From:
https://github.com/play-dl/play-dl/blob/f674b07e220272715b9f23c875bbf0091a2bd801/play-dl/YouTube/utils/extractor.ts#L103
To:
```js
if (response.alerts && response.alerts[0].alertRenderer?.type === 'ERROR') throw new Error(`While parsing playlist url\n   ${response.alerts[0].alertRenderer.text.runs[0].text}`)
```
(I added optional chaining on `alertRenderer`)

**Comment by killer069** [comment]
Nice Work. I will add this in latest release in 0.5.0

**Comment by killer069** [comment]
@Junhaochia 
Are you sure video unavailable crashes it or playlist unavailable crashes it ??

**Comment by Junhaochia** [comment]
> @Junhaochia
> Are you sure video unavailable crashes it or playlist unavailable crashes it ??

Yeah a unavailable video crashes it as shown in the output the simple text says: "1 unavailable video is hidden".
Tested the playlist in both locally (SG) [doesn't crash], and on the server host (EU) [crashes]. (video region issues) 

However, your fix justs throws (the alert was just an info alert telling us that there is some videos missing from the received list)
```
Error: While parsing playlist url 
Unknown Playlist Error
```
I think you can change your code from:
https://github.com/play-dl/play-dl/blob/5760ff3e9674769ade5155abe0d987c0b3d7b5db/play-dl/YouTube/utils/extractor.ts#L119-L122

To:
This codes looks through all the alerts and finds type 'ERROR' so that it throws when there is actually an error 
(and not other alert types like "INFO").
```ts
 if(response.alerts){
        response.alerts.forEach(alert => {
            if(alert.alertRenderer?.type === 'ERROR') throw new Error(`While parsing playlist url\n   ${alert.alertRenderer.text.runs[0].text}`)
            else if (Object.values(alert)[0].type === 'ERROR') throw new Error('While parsing playlist url\n Unknown Playlist Error')
        });
 } 
 ```

**Comment by Junhaochia** [comment]
Also youtube probably has playlist regex that sends us to the homepage instead of showing the invalid playlist alert
### This returns to homepage:
> On purpose:
> https://www.youtube.com/playlist?list=really_an_invaild_playlist
> By accidentally removing one character by accident:
> https://www.youtube.com/playlist?list=PLWkep-Lowk5mMYMtxT_gDFrfttifWYlH

### Instead of showing this page:
> https://www.youtube.com/playlist?list=PLWkep-Lowk5mMYMtxT_gDFrfttifWYlHD

### As a result, your package throws:
![image](https://user-images.githubusercontent.com/25685501/130616107-c355c2bc-336c-4ca0-a79f-c70104153c3d.png)

I didn't really bother fixing this one as wrapped the playlist_info with try and catch and tell the user that the playlist is invalid.

**Comment by killer069** [comment]
> On a side note: it is possible to move your github name to github bio. it isn't really informative of who is replying the email.
> ![image](https://user-images.githubusercontent.com/25685501/130618078-a1802476-8621-4b94-a88c-907644915a41.png)

Ok I changed my name, I forgot to change my username.



> Also youtube probably has playlist id regex that sends us to the homepage instead of showing the invalid playlist alert
> 
> ### This returns to homepage:
> > On purpose:
> > https://www.youtube.com/playlist?list=really_an_invaild_playlist
> > By accidentally removing one character by accident:
> > https://www.youtube.com/playlist?list=PLWkep-Lowk5mMYMtxT_gDFrfttifWYlH

So I guess I need to add one more parameter to check length of playlist ID.

**Comment by killer069** [comment]
@Junhaochia 
Released [v0.5.2](https://github.com/play-dl/play-dl/releases/tag/0.5.2)

Check if issues still persists or not

**Comment by killer069** [comment]
@Junhaochia 
Fixed all issues in 0.5.3

https://github.com/play-dl/play-dl/blob/5f4c19813a90123ea1adf816018859ef5906c5a9/play-dl/YouTube/utils/extractor.ts#L114-L124

Check if issue still persists or not.

**Comment by Junhaochia** [comment]
Yeah works, it validates the playlist Id properly now. 

Would be nice to have the option to allow incomplete playlist (ability to ignore the info alert about playlist containing unavailable videos). 

Rather than that all of the issues are fixed.

**Comment by killer069** [comment]
> Would be nice to have the option to allow incomplete playlist (ability to ignore the info alert about playlist containing unavailable videos).

@Junhaochia 
Check out v0.5.4

https://github.com/play-dl/play-dl/blob/353ff1e0f6fc4698efa223890c4116e70adc3aa3/play-dl/YouTube/utils/extractor.ts#L110

https://github.com/play-dl/play-dl/blob/353ff1e0f6fc4698efa223890c4116e70adc3aa3/play-dl/YouTube/utils/extractor.ts#L121-L124

Added parseIncomplete, so make sure to add `true` as a parameter while using `playlist_info`

It would be awesome, if you give us your feedback about this new package.

**Comment by Junhaochia** [comment]
It works as expected now, thanks @killer069 for the superb package and the speedy fix.

I don't think I have ran into any other issues as of now.

**Comment by killer069** [comment]
LOL, I forgot to make parseIncomplete optional
