### ISSUE TITLE
[=BUG=] Fails to parse unlisted youtube video basic info in versions >=1.0.0

### ISSUE THREAD

**Issue by ducktrshessami** [play-dl/play-dl#158]
#### Describe the bug

 - Node.js version: 16.6.2
 - OS & version: Windows 10

There's some trouble parsing the basic info for Youtube videos that wasn't previously in this package.

#### Actual behavior

`video_basic_info` produces the following error at `JSON.parse(player_data)`:
`SyntaxError: Unexpected token ; in JSON at position 55868`

I've noticed that the position number changes, but a log before parsing as JSON revealed the text that triggers the error is always the same:
```
;var meta = document.createElement('meta'); meta.name = 'referrer'; meta.content = 'origin'; document.getElementsByTagName('head')[0].appendChild(meta)
```
Tested on `0.9.9`, `1.0.0`, and `1.2.8`; only 0.9.9 did *not* have this issue.

#### Expected behavior

Removing the last bit of text from the unparsed JSON allowed the function to proceed with no further errors.
I imagine there was previously a way to detect unlisted videos or extra text in JSON that didn't make it to `1.0.0`

#### Code to reproduce

```js
const play = require("play-dl");

const url = "https://youtu.be/J5gbytKM5Us";

play.video_basic_info(url)
    .then(info => info.video_details.title)
    .then(console.log)
    .catch(console.error);
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
Wait let me do some testings.
