### ISSUE TITLE
[=BUG=] extractID() couldn't detect Youtube url

### ISSUE THREAD

**Issue by th13n-h4ck3r** [play-dl/play-dl#192]
#### Describe the bug
`extractID(url)` does not detect the following link `https://www.youtube.com/watch?v=_8ldAdQd9WU&list=RD-HRpDfAqe7w`

I have looked at the code, and `extractId(url)` uses `yt_validate(url)` and `yt_validate(url)` returns false; hence the error.

I think it's because `yt_validate(url)` looks for the `"list="` string, which the url does includes, so it thinks it's a playlist url, which tries to match the `playlist_pattern` [here](https://github.com/play-dl/play-dl/blob/a6ae318b1d2f0c872be1baa8124bce272cd4a113/play-dl/YouTube/utils/extractor.ts#L59), and ultimately fails because it's a mixed playlist.

 - Node.js version: v16.13.0
 - OS & version: Windows 10 x64

#### Actual behavior
`Error: This is not a YouTube url or videoId or PlaylistID`

#### Code to reproduce

```js
const playdl = require('play-dl');
const url = 'https://www.youtube.com/watch?v=_8ldAdQd9WU&list=RD-HRpDfAqe7w';
console.log(playdl.extractID(url));
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
If I try to parse video ID from those urls, then people will find it very difficult to extract playlist ID.

Those urls are considered as playlist urls.

Moreover playlist urls generated by a user are only supported in play-dl. Those generated by YouTube are out of scope for play-dl.
