### ISSUE TITLE
[=ASK=] How to search Spotify?

### ISSUE THREAD

**Issue by th13n-h4ck3r** [play-dl/play-dl#197]
#### What would you like to discuss?
Hi, I've been trying to search a track on Spotify but keep getting error.

I've followed the instruction posted [here](https://github.com/play-dl/play-dl/tree/main/instructions), but still getting the following error:
![image](https://user-images.githubusercontent.com/45925109/145893082-189edce0-05dc-412b-bc97-7933960713b1.png)

Please note that I have added a `console.log()`, so it can tell me the error code [here](https://github.com/play-dl/play-dl/blob/5a094be82ee837c173a988e8557bda3569102724/play-dl/Spotify/index.ts#L191-L193)
![image](https://user-images.githubusercontent.com/45925109/145893278-4646e095-6ca2-44cd-b60f-efb9b9ca36bd.png)

Here is my current code. 
![image](https://user-images.githubusercontent.com/45925109/145892916-dfdbee97-2c3d-43d9-9d3b-6ef319df8acb.png)

Also, I noticed that `refresh_token` is required, how do I get that? The instruction only showed how to get `CLIENT_ID` and `CLIENT_SECRET`.
#### Checklist

- [x] I have read the documentation.

**Comment by th13n-h4ck3r** [comment]
Thanks for the help!
I managed to get my refresh token that way. 

![image](https://user-images.githubusercontent.com/45925109/145933750-0ed22454-1ad7-43aa-b529-6b62c08835c8.png)

However, it still giving me the same error

![image](https://user-images.githubusercontent.com/45925109/145933515-02193ada-d3c9-4b05-80bc-d56b726e9bb3.png)

Also, the link I clicked, which I clicked authorized, redirects me to this page, which is normal right?

![image](https://user-images.githubusercontent.com/45925109/145933822-825d08c3-0d8a-4b0d-a562-63068bd1f603.png)

Here is my current code
![image](https://user-images.githubusercontent.com/45925109/145933959-9ea998b5-37f6-4029-868b-71f9423e6d92.png)

**Comment by killer069** [comment]
@th13n-h4ck3r 

Okay, so I made this `setToken` function sync. It should be async since I am making a request to get a valid token for the refresh Token. So maybe add a delay of 1 second after you run `setToken`. 

Doing that way will never work.

**Comment by killer069** [comment]
> Also, the link I clicked, which I clicked authorized, redirects me to this page, which is normal right?

This is normal page.

**Comment by killer069** [comment]
I created `setToken` function keeping in mind that discord.js takes some time to become ready. In your code, you are requesting search immediately after `setToken` function.

**Comment by th13n-h4ck3r** [comment]
I see, That makes sense. And I got it to work!

Thanks!

**Comment by killer069** [comment]
> I see, That makes sense. And I got it to work!
> 
> Thanks!

Glad to hear.

Welcome.

**Comment by bootleg-anonymous** [comment]
Hi, to follow up on the question, I've been trying to search Spotify **playlist** and **album,** but getting this error on this [line](https://github.com/play-dl/play-dl/blob/b94faef95712ca30a948f8083ebaf6322b605767/play-dl/Spotify/classes.ts#L238)

The error:
![image](https://user-images.githubusercontent.com/96161799/146130063-5731ff19-d38b-4463-a21b-ce5a1010d745.png)

This is `data.tracks` that it tries to read and get the error
![image](https://user-images.githubusercontent.com/96161799/146130592-d798e2fe-1e90-48a6-b17f-724bf5603b45.png)

What am I missing? I've looked at one of the similar closed issues [here](https://github.com/play-dl/play-dl/discussions/78#discussioncomment-1317623), but still unable to get it through as I'm not using `spotify()`

**Comment by killer069** [comment]
@bootleg-anonymous 

What is the spotify URL ??

I want to test myself.

**Comment by killer069** [comment]
> @bootleg-anonymous
> 
> What is the input ??
> 
> I want to test myself.

**Comment by bootleg-anonymous** [comment]
It's a search query string, not a url. So it has to be a url?

**Comment by killer069** [comment]
> It's a search query string, not a url. So it has to be a url?

Sorry, I meant what is the search query ??

**Comment by bootleg-anonymous** [comment]
> > It's a search query string, not a url. So it has to be a url?
> 
> Sorry, I meant what is the search query ??

Oh, anything would give me an error. In this case, I used `'lofi'`
![image](https://user-images.githubusercontent.com/96161799/146134280-3444b290-8555-4af3-98fe-1d1f90f8efaa.png)

**Comment by killer069** [comment]
This is a issue with the module. I will fix this soon.

**Comment by bootleg-anonymous** [comment]
Ok thanks! To be clear, this also happens when you search for album as well

**Comment by killer069** [comment]
> Ok thanks! To be clear, this also happens when you search for album as well

I know about that. Don't worry.

**Comment by killer069** [comment]
@bootleg-anonymous 

Hope your issue is fixed right now.

**Comment by bootleg-anonymous** [comment]
@killer069 

Everything works! It's just that whenever I do a search on for **album**, and `fetch()` the tracks, the `track.thumnail` is undefined. 

It's weird because there's no problem with it when searching for **playlist**.

Nonetheless, I alternatively use the `album.thumbnail` from the album object for the tracks, so it's all good.

**Comment by bootleg-anonymous** [comment]
Here is an example of what I explained above. It's not a problem, as I have found an alternative way for it already.

### Cannot fetch tracks from search results for `playlist` and `album`
```js
//search results
let results = await interaction.client.playdl.search('midnight to sunrise', {
    source: { spotify: 'album' },
    limit: 1,
});
//get the first result and fetch
let album = results[0];
await album.fetch();
//flat all the tracks into an array
let tracks = [...album.fetched_tracks.values()].flat();

console.log(tracks); //[]
```

### Solution: use `spotify()`
```js
//search results
let results = await interaction.client.playdl.search('midnight to sunrise', {
    source: { spotify: 'album' },
    limit: 1,
});
//use spotify() for the first result[0].url and fetch
let album = await interaction.client.playdl.spotify(results[0].url);
await album.fetch();
//flat all the tracks into an array
let tracks = [...album.fetched_tracks.values()].flat();

console.log(tracks); // (12) [x, x, x, x, x, x, x, x, x, x, x, x]
console.log(tracks[0].thumbnail) //undefined - However, thumbnail is undefined, but can use album.thumbnail as alternative
```
