### ISSUE TITLE
[=Feature=] SoundCloud Extractor

### ISSUE THREAD

**Issue by killer069** [play-dl/play-dl#2]
Create a SoundCloud Extractor (up to audio endpoint url)

**Comment by killer069** [comment]
This is still a question. Not Confirmed feature.

**Comment by killer069** [comment]
@cjh980402 

I just want a suggestion whether I should include this or not ??

Will you use this if it comes ??

**Comment by cjh980402** [comment]
I'm currently using another module for SoundCloud, so I'm willing to replace it with play-dl if you support SoundCloud.
