### ISSUE TITLE
Support for Twitch.tv Livestreams and VODs

### ISSUE THREAD

**Issue by mikeyaworski** [play-dl/play-dl#209]
#### What problem are you trying to solve?

Streaming audio from https://twitch.tv

#### Describe the feature

Are there plans to add support for Twitch livestreams? This library is the best I've found at supporting YouTube livestreams. I'm using `youtube-dl` for Twitch and YouTube VODs in my own bot at the moment, but that doesn't support livestreams. It would be great if this library had support for Twitch livestreams as well.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by killer069** [comment]
@mikeyaworski 

I think you mispelled YouTube videos in your description.

**Comment by killer069** [comment]
I will think about adding Twitch in play-dl tomorrow.

Will let you know about my decision in few days.

**Comment by killer069** [comment]
What are VODS ??

@mikeyaworski

**Comment by mikeyaworski** [comment]
VOD stands for Video On Demand. Basically videos which are not being livestreamed.

**Comment by killer069** [comment]
@mikeyaworski 

So I have decided that I will add Twitch in play-dl. But it will take some time. So Stay Tuned!

**Comment by mikeyaworski** [comment]
Great to hear!

**Comment by killer069** [comment]
So upon researching, I found out that it is quite difficult to implement a basic video clip stream also.

After some hours of testing, I was able to get a video clip access token. But I don't know where to use that.

So I dropped the idea of adding twitch as of now. If you can do some more research and tell me about how twitch works, only then I will be able to add support for Twitch.
