### ISSUE TITLE
[=BUG=] Cannot search certain youtube videos

### ISSUE THREAD

**Issue by bootleg-anonymous** [play-dl/play-dl#213]
#### Describe the bug
I recently found this [playlist](https://www.youtube.com/playlist?list=PLmDlycOoM-tuwy5WfaDRGo6cNNPfbHPRU) on Youtube.
For some reason, there are certain videos that cannot be retrieve via search using its url.
 - Node.js version: 1.6.2
 - OS & version: Windows x64

#### Actual behavior

It returns an empty array

#### Expected behavior

It should returns an array of results

#### Code to reproduce

```js
//urls that cannot be searched for some reason
const urls = ['https://www.youtube.com/watch?v=TKHuNMABus4','https://www.youtube.com/watch?v=ESRJu9TPN0Q','https://www.youtube.com/watch?v=2sTaRssnXhA','https://www.youtube.com/watch?v=MmFkBr9xhbw', 'https://www.youtube.com/watch?v=_X9SYhyyfDo', 'https://www.youtube.com/watch?v=OcMrmY0tX4M', 'https://www.youtube.com/watch?v=23KLqV29VyY','https://www.youtube.com/watch?v=TM8XnQeuj-Y'];
        
for(const url of urls){
    const results = await interaction.client.playdl.search(url, {
        source: { youtube: 'video' },
        limit: 1,
    });
    console.log(results); //[]
}
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
You search keywords not urls in `search` function.

For getting info from urls, use `video_info` function.

**Comment by bootleg-anonymous** [comment]
I see. I thought it was a bug because most of other urls I used it works. Like this [one](https://www.youtube.com/watch?v=dQw4w9WgXcQ), but not the ones I posted above

**Comment by bootleg-anonymous** [comment]
What happened here?
![image](https://user-images.githubusercontent.com/96161799/147046131-0433054b-5052-4c88-b379-eaeef46a474b.png)
![image](https://user-images.githubusercontent.com/96161799/147046149-bd0c0113-fc5c-475b-a71d-fd7d6f804127.png)

**Comment by killer069** [comment]
@bootleg-anonymous 

Docs are kinda messy right now. I will be fixing those in next update.

This happened because I enabled ESM default exports. So it mentions that I have re exporting stuff.
