### ISSUE TITLE
[=ASK=] Playing YouTube videos that have been tagged as inappropriate or offensive

### ISSUE THREAD

**Issue by Matei9721** [play-dl/play-dl#217]
#### What would you like to discuss?

I am wondering if it is possible to play youtube videos that are _ inappropriate or offensive to some audiences_. I have managed to play age-restricted videos by using cookies, but even after adding cookies, I was not able to bypass this error.
![image](https://user-images.githubusercontent.com/60573633/147411792-37202e46-a6be-48e0-82d6-270c9502829c.png)

I looked through the documentation and other issues, but I could not find anything related to this. I know this is aware as some other discord music bots are able to play these videos, I am not aware if play-dl has the ability to do so.

Thank you for the help!

#### Checklist

- [x] I have read the documentation.

- [x] Tried using cookies

**Comment by killer069** [comment]
I have seen a method to skip this offensive videos.

Can you provide the youtube url ??

**Comment by Matei9721** [comment]
@killer069 This is one example of link that throws the error: https://www.youtube.com/watch?v=47OC5rFeXGs

**Comment by Matei9721** [comment]
> I have seen a method to skip this offensive videos.
> 
> Can you provide the youtube url ??

Is skipping the video the only way? I know some bots like Mirai can play these videos so I suppose there must be a way to play the video instead of skipping.

**Comment by absidue** [comment]
Yes, it's possible to play those, we just need to implement what YouTube does when you click the button on the YouTube website.

**Comment by Matei9721** [comment]
> It's possible to play those, we just need to implement what YouTube does when you click the button on the YouTube website. Unlike the age restrictions, which need bypasses, this is just a warning popup, so it doesn't need a bypass, just support in play-dl.

Understandable. I am curious if you know whether this might be implemented in play-dl in the near future?

**Comment by absidue** [comment]
Yes, it will be.

**Comment by Matei9721** [comment]
Thank you, then I will be looking forward to the update!

> Yes, it will be.

**Comment by killer069** [comment]
Let this issue be opened until we fix the issue completely.

**Comment by Matei9721** [comment]
@killer069 @absidue  Another question regarding this issue, after the commit with the main, playing this song (https://www.youtube.com/watch?v=47OC5rFeXGs) still does not work.

Searching the youtube information about the song works:
![image](https://user-images.githubusercontent.com/60573633/147547013-3047e1e1-605d-4cb1-8844-65eaf742bb21.png)
In the output the new field is weirdly set to false even though for this song it should be true:
![image](https://user-images.githubusercontent.com/60573633/147547055-0cbad900-5fe4-49d0-b76f-4dcead057598.png)
But the error is thrown when trying to access the stream:
![image](https://user-images.githubusercontent.com/60573633/147547095-71b0789e-ed93-411f-ab66-6ee73f0a6a01.png)
![image](https://user-images.githubusercontent.com/60573633/147547116-768bac89-de1d-4045-b08b-2c62274509b1.png)

I can open a new issue if that is better, let me know!

**Comment by absidue** [comment]
Hi @Matei9721
You should be using `video_basic_info` or `video_info` when you want to get information about the video from a link. `search` returns the results on the search results page, which doesn't tell you if the video has the warning, i'll change the field it to be undefined for anything other than what is returned by `video_info` and `video_basic_info`, that means it will be undefined for search results, playlists, etc.

As for the stream creation not working, the current implementation relies on getting the cookies from cookie consent popup, which doesn't seem to be working (according to your GitHub profile you are in Europe, so theoretically the popup should be there), i'll do some more investigating as i've just realised it's broken outside of Europe.

**Comment by Matei9721** [comment]
> Hi @Matei9721 You should be using `video_basic_info` or `video_info` when you want to get information about the video from a link. `search` returns the results on the search results page, which doesn't tell you if the video has the warning, i'll change the field it to be undefined for anything other than what is returned by `video_info` and `video_basic_info`, that means it will be undefined for search results, playlists, etc.
> 
> As for the stream creation not working, the current implementation relies on getting the cookies from cookie consent popup, which doesn't seem to be working for you (according to your GitHub profile you are in Europe, so theoretically the popup should be there), i'll do some more investigating as i've also just realised it's broken outside of Europe.

Thanks, you are right, I forgot I need to use video_info.  I did try other videos tagged as offensive and indeed they work, so the error is specific to that one song for now. I am from Europe and I do get the pop-up on my browser. Thanks for looking into it!

**Comment by Matei9721** [comment]
For what it's worth, I changed my cookies from Romania with some from Italy and now the video plays. It's weird as I can play the video from Romania in the browser, but something might go wrong when trying to play it using the cookies using play-dl. 

At least I know it works with Italian cookies.

**Comment by killer069** [comment]
> At least I know it works with Italian cookies.

I think play-dl loves Italian cookies. 😂😂

**Comment by absidue** [comment]
This should be resolved in e24c43079002761e761d38c947ba5d5cedcdc3f4 and will be included in the next release, please let me know if you have any other issues with it.

**Comment by killer069** [comment]
@absidue 
[Line](https://github.com/play-dl/play-dl/blob/e24c43079002761e761d38c947ba5d5cedcdc3f4/play-dl/YouTube/classes/Video.ts#L164)
You could have done this line in a simple manner.

```ts
this.discretionAdvised = data.discretionAdvised ?? undefined
```

**Comment by Matei9721** [comment]
@absidue It seems that everything is working fine now. Thanks for the help with this issue, I think you can close it for good now :)

**Comment by Matei9721** [comment]
Hi @absidue @killer069 , sorry for pinging here again, but I have found another problem related to this issue. So I have been using this package( 1.7.3) on a bot and I found that I can play offensive videos where you need to accept that pop-up without any cookies. But then you can't play age-restricted videos without cookies so I added my cookies back using play.authentificate() and saving them in a file. Now the problem is that after adding cookies the offensive videos don't work again while the age-restricted ones work fine now.

This is the error I am getting with cookies saved in the .data folder (compare to before now I get this error no matter which country the cookies are from).
![image](https://user-images.githubusercontent.com/60573633/148220314-7d936dc9-34f1-4cb4-a795-7d5a771dd8c0.png)

If I take out the .data folder then offensive videos work fine, but the age-restricted ones won't work throwing the error that you need to log in to confirm your age.

I am sorry for annoying you again. Maybe I am doing something wrong when setting up the code?

**Comment by killer069** [comment]
@Matei9721 

Sorry for late reply. I was busy.

Will fix the issue in next update. Stay tuned!

**Comment by killer069** [comment]
@Matei9721 

Hope your issue is fixed in latest release.
