### ISSUE TITLE
[=ASK=]

### ISSUE THREAD

**Issue by jakepper** [play-dl/play-dl#221]
#### What would you like to discuss?

Hi, I am having trouble with the ```SpotifyPlaylist.page()``` method.

I receive the following error message,

```Error: Page number is not provided```

Using the code below,

```
const spotifyInfo = await playdl.spotify(url);
if (spotifyInfo.type === 'playlist') {
    await spotifyInfo.fetch();

    let count = 0;
    for (let i = 0; i <= spotifyInfo.total_pages; i++) {
        const page = spotifyInfo.page(i);
        for (const track of page) {
            const title = `${track.name} - ${track.artists[0].name}`;
            const video = await videoFinder(title);
            if (video) {
                songs.push({title: title, url: video.url});
                count++;
            }
        }
    }
  .
  .
  .
}
```

I am looping through the pages as described in the documentation and can't seem to figure out what I'm doing wrong.

Any help would be greatly appreciated, thanks!

#### Checklist

- [x] I have read the documentation.

**Comment by killer069** [comment]
Pages start from 1 not from 0

**Comment by jakepper** [comment]
Wow...totally though I had tried that. haha thanks!

**Comment by killer069** [comment]
HAHA 😁
