### ISSUE TITLE
[=BUG=] setToken for spotify not working

### ISSUE THREAD

**Issue by AbhayAysola** [play-dl/play-dl#229]
#### Describe the bug

 - Node.js version: v16.13.0
 - OS & version: Windows 10

`setToken()` method runs without any errors but `play.spotify` throws an error `Cannot read properties of undefined (reading 'spotify')`

#### Actual behavior
The `play.spotify()` method returns an error when using `setToken()` . (It works fine when I save the auth data in a file.)

#### Expected behavior
`setToken()` and saving auth data to file should work in the same way.

#### Code to reproduce

```js
play.setToken(spotify: {client_id: "client_id", client_secret: "client_secret", refresh_token: "refresh_token", market: "market});
play.spotify('spotify_url');
```

#### Additional information
I am using typescript

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by AbhayAysola** [comment]
Update: I looked through some of the issues and saw that `setToken()` actually takes sometime to save the data. So I put the setToken call near my bot login call and it works properly. Maybe you could make setToken() async, or tell the users to set it during initialization of the bot.

**Comment by Uximy** [comment]
> Update: I looked through some of the issues and saw that `setToken()` actually takes sometime to save the data. So I put the setToken call near my bot login call and it works properly. Maybe you could make setToken() async, or tell the users to set it during initialization of the bot.

Can you show me an example of where you added the code?

I also encountered this problem

**Comment by AbhayAysola** [comment]
I did setToken in the main index.js file where the bot is logged in. So,
```js
play.setToken(youtube: {}, spotify: {});
client.login(discord_token);
```
