### ISSUE TITLE
[=ASK=]

### ISSUE THREAD

**Issue by Hydreau** [play-dl/play-dl#242]
#### What would you like to discuss?
How to search for both video and playlist on Youtube (Not Channels) ?

#### Checklist
- I have read the documentation.

Current Code :
`const video = await play.search('NCS', { source: { youtube: "video" || "playlist" }, limit: 1 });`

It's basically always giving me a playlist and vice-versa if i put video at the end, i tried with another query "NPC rides his bike into the mayor" and it did the same thing

Thanks in advance.

**Comment by killer069** [comment]
You need to make 2 requests for getting video and playlist.

```ts
const video_search = await play.search('NCS', { source: { youtube: "video" }, limit: 1 });

const playlist_search = await play.search('NCS', { source: { youtube: "playlist" }, limit: 1 });
```

Reason : Youtube only allows us to choose type one at a moment.
