### ISSUE TITLE
[=BUG=] Premier videos not parsed correctly

### ISSUE THREAD

**Issue by killer069** [play-dl/play-dl#244]
### Discussed in https://github.com/play-dl/play-dl/discussions/243

<div type='discussions-op-text'>

<sup>Originally posted by **NovaLynxie** January 26, 2022</sup>
Hi there. I'm trying to add a playlist which, after inspecting the playlist links I used, I realised there is some playlist entries that are not actual videos and cause the stream URL function to throw an error doing so since they don't return a valid stream to playback.
An example playlist that (at the time of this post) have such entries is this one: [YouTube Playlist](https://www.youtube.com/playlist?list=PLrxcNWZXdQ2mizTQf5G8VfQvpO7t9oPQ_) (Image included below)
Is there a way to filter these out as it parses videos in the playlist to avoid my music bot erroring out playing these back after it adds the videos from the playlist?

![image](https://user-images.githubusercontent.com/21307676/151189099-2235f8c4-6415-4a35-8f21-06a59464a435.png)

Included is the code snippet below from my music command that handles my playlist parsing of songs from YouTube and SoundCloud respectively:
```js
    async function playlistParser(url, type) {
      let playlist, queue = [];
      try {
        if (type === 'yt') playlist = await playdl.playlist_info(url, { incomplete: true });
        if (type === 'so') playlist = await playdl.soundcloud(url);
      } catch (error) {
        logger.error('Failed to fetch playlist information!');
        logger.error(error.message); logger.debug(error.stack);
        throw error;
      };
      logger.verbose(`playlist:${JSON.stringify(playlist, null, 2)}`);
      if (playlist.tracks) {
        let song;
        for (let item of playlist.tracks) {
          if (item.fetched) { song = item } else {
            try {
              song = await playdl.soundcloud(`https://api.soundcloud.com/tracks/${item.id}`);
            } catch (error) {
              logger.error('Unable to fetch SoundCloudTrack information from requested playlist!');
              logger.error(error.message); logger.debug(error.stack);
              continue;
            };
          };
          logger.verbose(JSON.stringify(song, null, 2));
          queue.push({ title: song.name, duration: song.durationInSec, url: song.url, thumbnail: song.thumbnail, type: 'soundcloud' });
        };
      };
      if (playlist.videos) {
        let videos = await playlist.all_videos(); // <-- fetches all videos here.
        logger.verbose(`videos:${JSON.stringify(videos, null, 2)}`);
        for (let item of videos) { // <-- iterates over the videos here, pushing each one into the queue.
          logger.verbose(JSON.stringify(item, null, 2));
          /*
           * insert filter logic to skip over 'premiere' type videos here?
           */
          queue.push({ title: item.title, duration: item.durationInSec, url: item.url, thumbnail: item.thumbnails[item.thumbnails.length - 1].url, type: 'youtube' });
        };
      };
      logger.debug(`Parsed ${queue.length} songs! Adding them to music list.`);
      logger.verbose(`queue:${JSON.stringify(queue, null, 2)}`);
      return queue;
    };
```
Any help would be greatly appreciated.</div>

**Comment by killer069** [comment]
@NovaLynxie

Hope your issue is resolved.

**Comment by NovaLynxie** [comment]
@killer069 looks like the video I used as an example became a normal one, but will certainly test when I can find another one.
Thanks again for the help!

**Comment by NovaLynxie** [comment]
Update since last comment. Have now been able to test the fix properly.
Found another upcoming 'premiere' video and can confirm that I am able to filter out and prevent my bot from queueing premier/live videos after updating the play-dl dependency.

**Comment by killer069** [comment]
Glad to hear that.
