### ISSUE TITLE
Is there any way to bypass the youtube age restriction error?

### ISSUE THREAD

**Issue by benjaminaarsen** [play-dl/play-dl#246]
#### What would you like to discuss?
Hello, i am currently developing my own discord music bot (for me and my friends only). However the whole bot crashes when someone tries to play an age restricted track / video. Is there any way to check if the video is age restricted? Or can I bypass the age restriction in some way?

Hope someone can help :)

#### Checklist

- [ x] I have read the documentation.

**Comment by killer069** [comment]
https://github.com/play-dl/play-dl/tree/main/instructions#youtube-cookies

**Comment by benjaminaarsen** [comment]
Thing is I am currently 17 so I can't verify myself on youtube yet, thus can't get the cookies 😞

**Comment by killer069** [comment]
@benjaminaarsen 

Make a new account and change age to 18+.

Use the second account cookies for bot. EZ fix.

**Comment by benjaminaarsen** [comment]
I've tried exactly that but it still asks for a verification by credit card or id/drivers liscense :/

**Comment by benjaminaarsen** [comment]
I fixed it by catching the error that the YouTube video info function returns. And then trying to get the resource with sound cloud. Works pretty well
