### ISSUE TITLE
[=ASK=] `PlaylistOptions#incomplete` wrong description?

### ISSUE THREAD

**Issue by riflowth** [play-dl/play-dl#247]
#### What would you like to discuss?
[#playlist_info](https://play-dl.github.io/modules.html#playlist_info) parameter options (*PlaylistOptions*)
the description say `incomplete : If set to true, parses playlist with hidden videos` but when I pass false or leave it default for `incomplete` field it throw an exception below

```
Error: While parsing playlist URL x unavailable video is hidden
```

if I pass true for `incomplete` field is not throw an exception above and invoke `#all_videos` the array of videos which fetches from `#playlist_info` with incomplete true doesn't contain any hidden video and doesn't throw an exception

so it should be
`incomplete : If set to true, parses playlist without hidden videos` ???

#### Checklist

- [x] I have read the documentation.

**Comment by absidue** [comment]
I improved the documentation for that option in the latest release 1.8.3, hopefully that makes it clearer.

[playlist_info docs](https://play-dl.github.io/modules.html#playlist_info)
