### ISSUE TITLE
[=ASK=] Is there a way to play streams longer than 5 minutes?

### ISSUE THREAD

**Issue by Atkion** [play-dl/play-dl#26]
#### What would you like to discuss?
I saw that in 0.6.0 there was a loop point set to 5 minutes, and before that there were some crashing issues due to long streams.
Is there any plan to make long streams usable, or is it going to be capped at 5 minutes for the foreseeable future?

As a workaround, is there any way to grab a second stream starting at a certain time in the video as a way to simulate one long stream? (so I could grab 0:00-5:00, then a separate stream from 5:00-10:00, etc)

#### Checklist

- [x] I have read the documentation.

**Comment by killer069** [comment]
Actually the loop update was in 0.5.0. Where I started looping to avoid this [issue](https://github.com/discordjs/voice/discussions/188#discussioncomment-1219482). This looping makes long stream durable as seen [here](https://github.com/discordjs/voice/discussions/188#discussioncomment-1227284) and if you are on djs discord server, you can also see that someone also tested it for 45 mins [here](https://discord.com/channels/222078108977594368/852128888128929802/879635067918499850).

So this clearly states me that all looping works completely fine. I also tried myself for 25 mins and it was smooth.
If you have any ideas to loop it in better way, do let me know.

You need to learn about how data is sent in audio endpoint urls. The very first data we receive contains a audio head which contains all vital information. So if you want to grab a second stream from 5:00, you need to create a audio head which contains modified info about second stream and then only you will be able to play. So this is kinda tricky to be implemented. I am still looking for some ways to seek stream from a certain time.

If you could suggest me better ways, I will be happy to implement this in play-dl.

**Comment by killer069** [comment]
I think either you didn't tried to play long videos in 0.6.0 or you didn't understand loop completely.

That loop system came in 0.5.0 when people started facing this [issue](https://github.com/discordjs/voice/discussions/188#discussioncomment-1219482). So for that time being, I made a loop which will loop 270 seconds [ aka 30 seconds before 5 mins mark ]. Then I raised it to 290 seconds [ aka 10 seconds before 5 mins ].

In latest update, I have created a loop [ first data when it is created ] which will get second stream data at 290 seconds. And then onwards, it will loop at 300 seconds [ aka 5 minutes ]. This makes every loop to get data 10 seconds before playing stream reaches 5 mins mark. This is all good for long playback. Try it yourself.

**Comment by Atkion** [comment]
You're right, I didn't quite understand what you meant by a loop. 
I still believe there might be a problem, however. Today, I tried two different longer streams, and one of them worked while the other didn't. 

The first one was [this](https://www.youtube.com/watch?v=3oypmjuiM0E&ab_channel=LouSays), and I was able to get over 25 minutes into it with no issues. 

The one that originally prompted this issue, however, was [this](https://youtu.be/pBC_sYtjykU). Instead of continuing seamlessly, this one loops back to the beginning of the video every 290 seconds. I ran this for an hour (longer than the video itself), and it kept looping the same 290-second clip infinitely.
See if you can reproduce it; I'm not sure what would make this video any different from any other, but I'll continue looking and try to make sure it isn't a flaw in my code somewhere.
This behavior is consistent with this video, and my play-dl version is 0.6.1.

**Comment by killer069** [comment]
Released v0.6.2

Check if it still exists or not.

**Comment by Atkion** [comment]
Whatever you did seems to have worked!

That video now plays without issue.
Thanks :)

**Comment by killer069** [comment]
@Atkion 
Actually I assumed that before getting the second data [ after 290 seconds ] , stream should be played more than 300 seconds. 
But in this case, it didn't. The playback was stopped at 285 seconds mark as per my testing. 

So I reduced the seconds data timing to 280 seconds.

I am still failing to understand how did you got loop of first 290 seconds. Since on my testing, AudioPlayer stopped at 285 seconds mark for me and after that there was no audio.

**Comment by Atkion** [comment]
I'm afraid I don't understand how AudioPlayer or the stream works well enough to guess the difference. Maybe we have them set up with different behaviors if yours simply stopped instead of looping?

I also was not timing it very precisely, perhaps it looped at 285 and my hardware was slow enough to add a few seconds of silence before looping?

**Comment by killer069** [comment]
> I'm afraid I don't understand how AudioPlayer or the stream works well enough to guess the difference. Maybe we have them set up with different behaviors if yours simply stopped instead of looping?
> 
> I also was not timing it very precisely, perhaps it looped at 285 and my hardware was slow enough to add a few seconds of silence before looping?

No issue, at least the issue is solved 👍
