### ISSUE TITLE
[=FEATURE=] non API URL in SoundCloud classes

### ISSUE THREAD

**Issue by arnokeesman** [play-dl/play-dl#260]
#### What problem are you trying to solve?

Getting a link for SoundCloud tracks that users can use.

#### Describe the feature

SoundCloudTrack#permalink

```js
track.permalink;
```
example output: https://soundcloud.com/monstercat/noisestorm-crab-rave
this value is given by the SoundCloud API, value is called `permalink_url`

#### Checklist

- [X] I have read the documentation and made sure this feature doesn't already exist.

**Comment by absidue** [comment]
This was implemented in 1.8.9.
