### ISSUE TITLE
[=BUG=] HTTPError: Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by cjh980402** [play-dl/play-dl#27]
#### Describe the bug

 - Node.js version: 16.6.2
 - OS & version: ubuntu 20.04

```
node:events:371
      throw er; // Unhandled 'error' event
      ^

HTTPError: Response code 403 (Forbidden)
    at Request._onResponseBase (/home/ubuntu/bot/node_modules/got/dist/source/core/index.js:899:31)
    at Request._onResponse (/home/ubuntu/bot/node_modules/got/dist/source/core/index.js:934:24)
    at ClientRequest.<anonymous> (/home/ubuntu/bot/node_modules/got/dist/source/core/index.js:948:23)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.origin.emit (/home/ubuntu/bot/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:621:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:394:28)
Emitted 'error' event on Request instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: undefined,
  timings: {
    start: 1630298022597,
    socket: 1630298022597,
    lookup: 1630298022678,
    connect: 1630298022680,
    secureConnect: 1630298022685,
    upload: 1630298022686,
    response: 1630298022688,
    end: 1630298022689,
    error: undefined,
    abort: 1630298022690,
    phases: {
      wait: 0,
      dns: 81,
      tcp: 2,
      tls: 5,
      request: 1,
      firstByte: 2,
      download: 1,
      total: 93
    }
  }
}
```
I got this error even if I handled error event of AudioPlayer(discordjs/voice)

#### Code to reproduce

```js

```

#### Checklist

- [o] I have read the documentation.
- [o] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
This will be fixed once I update got to v12.

So please wait for 0.7.0 update.

If you can get this error consistently, do let me know the url.

This is not a consistent error. So not a thing to worry about.

**Comment by cjh980402** [comment]
I see, then when will the 0.7.0 update be made? This libarary is good choice coz light-weight.

**Comment by killer069** [comment]
> I see, then when will the 0.7.0 update be made? This library is good choice coz light-weight.

Just in few days.
Stay Tunned

**Comment by killer069** [comment]
It appears this error is very rare. So fixing this issue, just force me to create a new loop and that will take a lot of time.

So this is not going to be easy to tackle. So for now, I am just putting this as later.

**Comment by cjh980402** [comment]
Okay... However, I experienced this error at least one time when I play  about 20 songs.

**Comment by killer069** [comment]
> Okay... However, I experienced this error at least one time when I play about 20 songs.

Okay, Fixed in latest developer build.

**Comment by killer069** [comment]
@cjh980402 

Check [this](https://github.com/play-dl/play-dl/tree/developer#streamurl--string-error_check--boolean)

**Comment by cjh980402** [comment]
Okay, I'm testing developer branch.

**Comment by killer069** [comment]
> Okay, I'm testing developer branch.

Make sure to add true in the code

**Comment by cjh980402** [comment]
I tested developer branch(add true in the stream code), error doesn't occured. It would be fixed.

**Comment by killer069** [comment]
Released 0.6.9

Fixed all errors

**Comment by killer069** [comment]
@cjh980402 

Please see the latest commit, add retry to true to completely remove 403

[StreamOptions](https://github.com/play-dl/play-dl/tree/main/docs/YouTube#streamoptions)

**Comment by killer069** [comment]
Will fix this in next update.

Still some things are missing.

**Comment by killer069** [comment]
Finally got the mistake. Now Error 403 will never occur

**Comment by killer069** [comment]
@cjh980402 

Fixed this issue, no need to set any value to true now.

**Comment by cjh980402** [comment]
Thanks!

**Comment by killer069** [comment]
@cjh980402 

I need further testing to see whether this is solved or not,

Please let me know if you got this error again.

**Comment by killer069** [comment]
Finally, can confirm that it retries once it hits 403 in latest release 

![image](https://user-images.githubusercontent.com/65385476/132211376-c33ba179-af32-48ed-b0e6-9a4dd797202d.png)

See the 2.7 seconds of playing a song.

Finally achieved it.

@cjh980402
