### ISSUE TITLE
[=ASK=] Slow Download Speed

### ISSUE THREAD

**Issue by sametserpil** [play-dl/play-dl#271]
Download speed is very slow compared to ytdl-core. Am I missing something or is it by design?

#### Checklist

- [ -] I have read the documentation.

**Comment by AtariTom** [comment]
It's by design, play-dl is mostly intended for streaming audio to discord, meaning it doesn't need fast download speeds. It doesn't decipher the n param of the download URL, so the download speeds remain slow.

**Comment by sametserpil** [comment]
> It's by design, play-dl is mostly intended for streaming audio to discord, meaning it doesn't need fast download speeds. It doesn't decipher the n param of the download URL, so the download speeds remain slow.

Thank you for the info.
