### ISSUE TITLE
[=BUG=] Error: Got 401 from the request

### ISSUE THREAD

**Issue by MrCheatEugene** [play-dl/play-dl#285]
#### Describe the bug

 - Node.js version: 16.14.0
 - OS & version: Ubuntu 18.04, I don't know what my play-dl version is..

When I am trying to get audio stream from this spotify song, I get error.
#### Actual behavior
```Error: Got 401 from the request
    at /test/musicbot/node_modules/play-dl/dist/index.js:1:4080
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```
<!-- Actual behavior -->

#### Expected behavior

<!-- Expected behavior --> 
I expected for it to give me an audio stream, but instead it gave me an error.
#### Code to reproduce

```js
        let stream = await play.stream("https://open.spotify.com/track/7CCCX50zGHMTuHsyKQy03l");
```
#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by AtariTom** [comment]
This isn't a bug, you can't stream from Spotify. Consider using `spotify(url)` to get the song info, and then passing it through the `search` function and so on to get the youtube stream data.

**Comment by absidue** [comment]
As @AtariTom stated streaming from Spotify is not supported and support won't be added (see https://github.com/play-dl/play-dl/issues/210 for more details). I recommend updating your play-dl version as newer versions than the one you are using throw an error telling you that streaming from Spotify is not supported.
