### ISSUE TITLE
[=BUG=] Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by EasyXploit** [play-dl/play-dl#300]
#### Describe the bug

 - Node.js version: 17.5.0
 - OS & version: Ubuntu 20.04.4 LTS & play-dl v1.9.5

The `playlist_info` method is not capable of playing some (not all) YouTube playlists, and I suspect this is only the case for playlists that have some live video. This problem occurs to me, for example, with the playlist [https://www.youtube.com/watch?v=xVQgD6QG2Zc&list=PL6fhs6TSspZv0F0YgsG-p7Mn189CU2XKS](https://www.youtube.com/watch?v=xVQgD6QG2Zc&list=PL6fhs6TSspZv0F0YgsG-p7Mn189CU2XKS)

#### Actual behavior

I get the following TypeError:
```js
TypeError: Cannot read properties of undefined (reading 'style')
    at getWatchPlaylistVideos (/***/***/***/node_modules/play-dl/dist/index.js:7:4338)
    at getWatchPlaylist (/***/***/***/node_modules/play-dl/dist/index.js:7:1041)
    at Object.playlist_info (/***/***/***/node_modules/play-dl/dist/index.js:6:60)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.exports.run (/***/***/***/utils/voice/parsePlaylist.js:7:26)
```

#### Expected behavior

The method should return what is detailed in its documentation.

#### Code to reproduce

```js
const playdl = require('play-dl');
const playlistUrl = 'https://www.youtube.com/watch?v=xVQgD6QG2Zc&list=PL6fhs6TSspZv0F0YgsG-p7Mn189CU2XKS';
const playlist = await playdl.playlist_info(playlistUrl); //<--- Error obtained here
```

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by AtariTom** [comment]
Added small check for the thumbnail overlay badge. (see https://github.com/play-dl/play-dl/commit/f974e1f9241a2e096809236c98bbbf6e8154f758), should work now.

**Comment by EasyXploit** [comment]
Cool! I even learned what optional chaining is thanks to your commit 😄
