### ISSUE TITLE
[=BUG=] RequestError: read ECONNRESET (rarely bug)

### ISSUE THREAD

**Issue by cjh980402** [play-dl/play-dl#31]
#### Describe the bug

 - Node.js version: 16.6.2
 - OS & version: ubuntu 20.04

```
node:events:371
      throw er; // Unhandled 'error' event
      ^

RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/home/ubuntu/bot/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.origin.emit (/home/ubuntu/bot/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:211:20)
Emitted 'error' event on Request instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET',
  timings: {
    start: 1630408508781,
    socket: 1630408508782,
    lookup: 1630408508782,
    connect: 1630408508785,
    secureConnect: 1630408508789,
    upload: 1630408508789,
    response: 1630408508799,
    end: undefined,
    error: 1630408590273,
    abort: 1630408590274,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 3,
      tls: 4,
      request: 0,
      firstByte: 10,
      download: undefined,
      total: 81493
    }
  }
}
```
In before issue, I ignore ECONNRESET error to add When I add `stream.once('error', () => {});` or `stream.once('error', () => { stream.destroy(); });` in Stream.normal_start(), Stream.loop_start(), Stream.loop(), and etc.
Can it be solution about this rarely bug?
#### Code to reproduce

```js

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
This happened in mid stream ???

**Comment by killer069** [comment]
What were the conditions when this happened ??

Like I want to know :
- video url
- when did it happen (start or mid or end) ??

**Comment by cjh980402** [comment]
First it was uncaught exception.
url: https://www.youtube.com/watch?v=XltOvoRqFqE
when did it happen: maybe start

It's not accurate because it's an uncatched error, but the above conditions are maybe correct.

**Comment by killer069** [comment]
> First it was uncaught exception.

Adding this will cause more trouble, since then people will don't know why their stream ended without any reasons.
`stream.once('error', () => {});`

And talking about `ECONNRESET` error, "ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. So other side means, google site closed it abruptly. So I can't do anything about this.

**Comment by cjh980402** [comment]
Oh, I see. Then, how can I handled that error outside of play-dl? try-catch doesn't catch that error.

**Comment by killer069** [comment]
> Oh, I see. Then, how can I handled that error outside of play-dl? try-catch doesn't catch that error.

For handling the error, I may emit this error to actual stream in 0.7.3.

**Comment by cjh980402** [comment]
I think your solution is the best :)
Thanks!

**Comment by killer069** [comment]
@cjh980402 

Now instead of giving uncaught exception. It will give a AudioPlayer Error if it occurs.
