### ISSUE TITLE
[=ASK=] About spotify refresh token

### ISSUE THREAD

**Issue by Olebeh** [play-dl/play-dl#320]
#### What would you like to discuss?
How do i fetch tracks using spotify() if the token expires so quickly? Is there a way to make it last longer and not getting 401 error every 5 minutes?

#### Checklist

- [✓] I have read the documentation.

**Comment by adamk33n3r** [comment]
According to the [spotify docs](https://developer.spotify.com/documentation/general/guides/authorization/code-flow/) the tokens should last an hour.

**Comment by Olebeh** [comment]
> According to the [spotify docs](https://developer.spotify.com/documentation/general/guides/authorization/code-flow/) the tokens should last an hour.

Any way to make it last longer?

**Comment by adamk33n3r** [comment]
> > According to the [spotify docs](https://developer.spotify.com/documentation/general/guides/authorization/code-flow/) the tokens should last an hour.
> 
> Any way to make it last longer?

No, this is pretty standard on the web. You can just wrap all of your requests in a check to automatically refresh it and you won't even notice.

**Comment by Olebeh** [comment]
> > > According to the [spotify docs](https://developer.spotify.com/documentation/general/guides/authorization/code-flow/) the tokens should last an hour.
> > 
> > 
> > Any way to make it last longer?
> 
> No, this is pretty standard on the web. You can just wrap all of your requests in a check to automatically refresh it and you won't even notice.

Just realized there is refresh_token() function. And it works

**Comment by adamk33n3r** [comment]
Oh yes, you see in the example here https://github.com/play-dl/play-dl/blob/ce9c57460701535ca077f479fb9c9c2d88fa0c7f/examples/Spotify/play.js#L21 that you can check if it's expired and refresh it every time you get an interaction.
