### ISSUE TITLE
[=BUG=] Cannot read properties of undefined (reading 'defaultIcon')

### ISSUE THREAD

**Issue by MikeDev96** [play-dl/play-dl#321]
Getting the following error randomly:

`Cannot read properties of undefined (reading 'defaultIcon')`

This is when running on Ubuntu, when trying to recreate in dev on my machine (Windows) it's fine...

Here's some links it was happening for:

https://www.youtube.com/watch?v=HWQR-hAJrKU
https://www.youtube.com/watch?v=vUv7UpJcJ2Y
https://www.youtube.com/watch?v=kobLm8hGll8

Can we maybe get a null check on that prop please?

I believe this is the offending line: https://github.com/play-dl/play-dl/blob/ce9c57460701535ca077f479fb9c9c2d88fa0c7f/play-dl/YouTube/utils/extractor.ts#L285

**Comment by wolf-yuan-6115** [comment]
Same here

**Comment by Pixwl** [comment]
Can confirm that this is happening on Ubuntu 20.04 LTS and Windows 11 (version 22H2).

**Comment by b2saspect** [comment]
Same here

**Comment by adamk33n3r** [comment]
Getting this for the lofi hip hop livestream which has been working for weeks prior to recently. 
https://www.youtube.com/watch?v=jfKfPfyJRdk

**Comment by Pokepeople02** [comment]
Can also confirm this is happening on Windows 10 (21H2) with Node v16.17.0 and play-dl v1.9.5. It seems to happen spontaneously with random YT videos. Sometimes retrying immediately after the error works without issue, while other times it may happen multiple times in a row for a single request, rarely (if ever) erroring more than twice for a single video before working correctly.

**Comment by PapiOphidian** [comment]
This bug is known and a fix is currently being worked on. Not by myself, but by Atari Tom. No ETA has been provided

**Comment by AtariTom** [comment]
Fixed in fc6007b472625838b02631692297f9685b39a426
