### ISSUE TITLE
[=BUG=] Playing age restricted video gives 410 error

### ISSUE THREAD

**Issue by MVDW-Java** [play-dl/play-dl#33]
#### Describe the bug

 - Node.js version: v16.8.0
 - OS & version: Ubuntu 18.04.5 LTS

#### Actual behavior
I'm trying to play a video that is age restricted but I am getting an error and video does not play on my Discord bot.

#### Expected behavior
Playing the video without problems and no error in console.

 

#### Code to reproduce

```js

```

#### ScreenShots

![image](https://user-images.githubusercontent.com/22998325/131723170-6c56c817-2cb1-4ad8-840e-affa2536d291.png)

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
Age Restricted Videos are out of scope for play-dl.

Maybe check out other youtube alternatives which allows you to login.

**Comment by killer069** [comment]
BTW, it should never give 410 error.

Please make sure you are on latest play-dl version.

**Comment by killer069** [comment]
It should give this error. @MVDW-Java 

![image](https://user-images.githubusercontent.com/65385476/131775775-9f1a041e-cdb1-437f-af04-5746bec2a1a1.png)

**Comment by killer069** [comment]
Now I am planning to add this in 0.7.6

@MVDW-Java

**Comment by killer069** [comment]
@MVDW-Java 
0.7.6 Released

Please see [ finding cookies ](https://github.com/play-dl/play-dl/discussions/34) here and a [example](https://github.com/play-dl/play-dl/blob/main/examples/play%20-%20cookies.js) for playing age restricted videos
