### ISSUE TITLE
[=BUG=] Memory leak

### ISSUE THREAD

**Issue by i1u5** [play-dl/play-dl#333]
#### Describe the bug

 - Node.js version: 18.12.1 LTS
 - OS & version: **Debian 11 (bullseye)**, play-dl v1.9.6

It seems that the buffer (or whatever it is) created by play-dl.stream() doesn't get garbage collected so the tracks stay on memory until streaming stops all together, so longer yt videos (becomes obvious around 30mins) keep allocating more RAM until the process hangs
This was noticed on the following videos at least:
https://www.youtube.com/watch?v=g8ATt1N5nrU
https://www.youtube.com/watch?v=9ou1pl0XNRs

Limiting node's heap size with `--max_old_space_size` doesn't help either.

#### Actual behavior
Sometimes this warning is thrown after an hour or so
```
(node:538) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [WebmSeeker]. Use emitter.setMaxListeners() to increase limit
```
And sometimes the process just crashes at some point
#### Expected behavior

The memory is expected to stabilize around some point during the stream, plus I don't really think it would even require close to 100mb for a single stream, let alone ~400mb.

#### Code to reproduce
https://gist.github.com/i1u5/c8fd83f13f4c8a9719361553d275af2d (an exact copy of the search example in the repo)

#### ScreenShots
![image](https://user-images.githubusercontent.com/26717942/202490396-6be5ecc0-08e4-4751-b1b3-05270eb016ef.png)
![image](https://media.discordapp.net/attachments/888999501526880256/1042456265793749002/image.png)

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by i1u5** [comment]
Turns out it's an issue with [@discordjs/voice ](https://github.com/discordjs/discord.js/tree/main/packages/voice)
Possibly related: https://github.com/discordjs/voice/issues/164

**Comment by vzakharov** [comment]
@i1u5 (or anyone), were you able to find a solution? @discordjs/voice is archived, so I can't comment there, but the thing is happening to me right now and it's annoying.

**Comment by i1u5** [comment]
> @i1u5 (or anyone), were you able to find a solution? @discordjs/voice is archived, so I can't comment there, but the thing is happening to me right now and it's annoying.

I switched to Eris.js, since it can play them without djs/voice, but it's a pretty much obsolete library (does the job but w/ some errors), theres a more modern library called Oceanicjs but it uses djs/voice too so sadly the only choice here is Eris.
