### ISSUE TITLE
[=BUG=] This is not a Spotify URL Error

### ISSUE THREAD

**Issue by GamerMine** [play-dl/play-dl#358]
#### Describe the bug

 - Node.js version: v20.5.1
 - OS & version: Debian 11 (bullseye)

I am using play-dl to get informations about a spotify song. I am using the link that I get by right clicking on a song and using the "Copy song link" under "Share".
I did not make any changes to any other packages that I use and it still works with playlist.

#### Actual behavior

Return an error : Error: This is not a Spotify URL

#### Expected behavior

Expecting to get the data from the link.

#### Code to reproduce

```js
if (play.is_expired()) await play.refreshToken();
let sp_data = await play.spotify(link)
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.
- [x] Tried to re-run authorize() with a fresh client id and client secret
- [x] Tried two different systems with same behavior

**Comment by AtariTom** [comment]
>I am using play-dl to get informations about a spotify song. I am using the link that I get by right clicking on a song and using the "Copy song link" under "Share".

Could you supply the link that caused the error? (or a link if many trigger this error)

**Comment by GamerMine** [comment]
Ahnk you for your response. Here is a link that trigger this error : 
https://open.spotify.com/intl-fr/track/2SCP5oOX5OSp5RT83h2rs0?si=4e1b609f1b12403c

Basically any track link is trigggering this error

**Comment by atrtom** [comment]
Added regex support for these links (and hopefully it'll work with other markets): 6a8569f
