### ISSUE TITLE
[=BUG=] Soundcloud 403 Error

### ISSUE THREAD

**Issue by brhndursun** [play-dl/play-dl#359]
SoundCloud/index.ts getFreeClientID function not working.
I've got 403 error also <script crossorigin src=" not found on soundcloud.com.
Need another way to get clientid.

I'll write more information about this issue if you're interested and need more info. So far, this could be enough.

**Comment by AtariTom** [comment]
To clarify; For some reason soundcloud now expects user-agents, failing to provide any results in a 403 from `https://soundcloud.com`.
The is the fix: `await request('https://soundcloud.com/', {headers: {}})` (SoundCloud/index.ts L.114)

**Comment by atrtom** [comment]
Fixed in 6a8569f
