### ISSUE TITLE
[=BUG=] Length of some playlist id isnt' 34

### ISSUE THREAD

**Issue by cjh980402** [play-dl/play-dl#41]
#### Describe the bug
1st URL: https://www.youtube.com/watch?v=UclSNeLc2aI&list=FLMalFh3zoiVTPWqg-5lx8-Q
length of id: 24

2nd: URL: https://www.youtube.com/watch?v=FZu097wb8wU&list=RDFZu097wb8wU
length of id: 13

I found some link about youtube id. (https://linuxpanda.wordpress.com/2013/07/24/ultimate-best-regex-pattern-to-get-grab-parse-youtube-video-id-from-any-youtube-link-url/)

#### Code to reproduce

```js

```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
> 1st URL: https://www.youtube.com/watch?v=UclSNeLc2aI&list=FLMalFh3zoiVTPWqg-5lx8-Q
> length of id: 24

This type of url is created by youtube, not by actual user. You can try see your Liked Videos playlist also.

So play-dl supports url that has been made by actual user.

Try creating a new playlist, you will be given a 34 length playlist ID starting with 'PL'

> 2nd: URL: https://www.youtube.com/watch?v=FZu097wb8wU&list=RDFZu097wb8wU
> length of id: 13

This url is also created by youtube only. The videos in this playlist are relative to a particular users.

These playlist are temporary for a user. That means that you can't get a actual playlist url in the format like :

```
https://www.youtube.com/playlist?list=<Playlist ID>
```

**Comment by cjh980402** [comment]
Oh, I see. That's the reason why length isn't 34.
