### ISSUE TITLE
[=BUG=] Playlist info error

### ISSUE THREAD

**Issue by Samiul30** [play-dl/play-dl#43]
#### Describe the bug

 - 16.x.x 
 - Windows 10 pro: 

The bug is related to playlist info with playlist_info function which return `video_id = url.split('watch?v=')[1].split('&')[0];` as err!

#### Actual behavior
Throws err `video_id = url.split('watch?v=')[1].split('&')[0];` 
#### Expected behavior
It should return the playlist data.

#### Code to reproduce

```js
  yt.playlist_info(query) .then(output =>
    
    
        { 
        console.log(output)
         console.log(`yes used! playlist_url`)
         return {
             title: output.title,
             duration: output.durationInSec * 1000,
             thumbnail: output.thumbnail,
             engine: yt.stream_from_info(output).then(m=>m),
             views: output.views,
             author: output.channel,
             description: output.description,
             url: output.url}
             
         } 
         );
```

#### Checklist

- [ .] I have read the documentation.
- [. ] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
Url of playlist please ??

**Comment by killer069** [comment]
Your code has issues. Not my play-dl

**Comment by Samiul30** [comment]
> Your code has issues. Not my play-dl
> 
> First see the output and change your code accordingly.

The err comes from play dl...not from any of my files

**Comment by killer069** [comment]
> The err comes from play dl...not from any of my files

Your code `yt.stream_from_info(output).then(m=>m)` is completely wrong.
