### ISSUE TITLE
Playlist Bug

### ISSUE THREAD

**Issue by Samiul30** [play-dl/play-dl#44]
#### Describe the bug

 - Node.js version: 
 - OS & version: 

                throw new Error(`While parsing playlist url\n   ${response.alerts[0].alertWithButtonRenderer.text.simpleText}`);
                      ^

Error: While parsing playlist url
   অনুপলভ্য ভিডিওগুলি আড়ালে আছে
    at Object.playlist_info (E:\Work\DISCORD JS\Working Files\oculetbot\node_modules\play-dl\dist\YouTube\utils\extractor.js:130:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

#### Code to reproduce

```js

```

#### Checklist

- [ ] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by Samiul30** [comment]
> #### Describe the bug
> * Node.js version:
> * OS & version:
>   ```
>            throw new Error(`While parsing playlist url\n   ${response.alerts[0].alertWithButtonRenderer.text.simpleText}`);
>                  ^
>   ```
> 
> Error: While parsing playlist url
> অনুপলভ্য ভিডিওগুলি আড়ালে আছে
> at Object.playlist_info (E:\Work\DISCORD JS\Working Files\oculetbot\node_modules\play-dl\dist\YouTube\utils\extractor.js:130:23)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> #### Actual behavior
> #### Expected behavior
> #### Code to reproduce
> #### ScreenShots
> #### Checklist
> * [ ]  I have read the documentation.
> * [ ]  I have tried my code with the latest version of Node.js and Play-dl.

If you like to close the issues you can it won't help you that much to fix your package without reproducing it!!!

**Comment by killer069** [comment]
Please set parseIncomplete to true while running playlist_info code.

See [here](https://github.com/play-dl/play-dl#playlist)

Your translated words :-
![image](https://user-images.githubusercontent.com/65385476/132117405-cc4d0fee-f41a-42a9-81af-782480bfea40.png)

**Comment by killer069** [comment]
I have done many tests before making it. So please read docs completely. 

Don't create issues without reading docs completely.

**Comment by Samiul30** [comment]
> I have done many tests before making it. So please read docs completely.
> 
> Don't create issues without reading docs completely.

If it is false for parseIncomplete it should return somthing....rather than err

**Comment by killer069** [comment]
> > I have done many tests before making it. So please read docs completely.
> > Don't create issues without reading docs completely.
> 
> If it is false for parseIncomplete it should return somthing....rather than err

It will never. If you are getting errors, why would it return something ??

**Comment by Samiul30** [comment]
> > > I have done many tests before making it. So please read docs completely.
> > > Don't create issues without reading docs completely.
> > 
> > If it is false for parseIncomplete it should return somthing....rather than err
> 
> It will never. If you are getting errors, why would it return something ??

const playlist = await playlist_info(url)
//This only fetches first 100 videos from a playlist
 You wrote it in the doc and according to it it shouldn't provide err

**Comment by killer069** [comment]
> > > > I have done many tests before making it. So please read docs completely.
> > > > Don't create issues without reading docs completely.
> > > 
> > > 
> > > If it is false for parseIncomplete it should return somthing....rather than err
> > 
> > 
> > It will never. If you are getting errors, why would it return something ??
> 
> const playlist = await playlist_info(url)
> //This only fetches first 100 videos from a playlist
> You wrote it in the doc and according to it it shouldn't provide err

That is for normal playlist without errors.

Like [these ones](https://www.youtube.com/playlist?list=PLUt3leKZfbZqLzLwcQMYPBdbe7i7KRCOP)

**Comment by Samiul30** [comment]
> > > > > I have done many tests before making it. So please read docs completely.
> > > > > Don't create issues without reading docs completely.
> > > > 
> > > > 
> > > > If it is false for parseIncomplete it should return somthing....rather than err
> > > 
> > > 
> > > It will never. If you are getting errors, why would it return something ??
> > 
> > 
> > const playlist = await playlist_info(url)
> > //This only fetches first 100 videos from a playlist
> > You wrote it in the doc and according to it it shouldn't provide err
> 
> That is for normal playlist without errors.
> 
> Like [these ones](https://www.youtube.com/playlist?list=PLUt3leKZfbZqLzLwcQMYPBdbe7i7KRCOP)

https://youtube.com/playlist?list=PLRBp0Fe2GpgmbpTy0fNGpoEtEzcDJ1IgQ this one?

**Comment by killer069** [comment]
> https://youtube.com/playlist?list=PLRBp0Fe2GpgmbpTy0fNGpoEtEzcDJ1IgQ this one?

No Errors in this one

![image](https://user-images.githubusercontent.com/65385476/132117698-f343f168-39b7-4460-8d9b-316ee9161da4.png)
