### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by killer069** [play-dl/play-dl#45]
### Discussed in https://github.com/play-dl/play-dl/discussions/42

<div type='discussions-op-text'>

<sup>Originally posted by **cjh980402** September  4, 2021</sup>
When the bot started, bot process memory usage is about 14%.
When the bot is running about 23 hours, bot proccess memory usage is about 40%.
![image](https://user-images.githubusercontent.com/23624124/132098833-ada51256-673c-4d06-9d86-9c4134242034.png)
above picture is memory usage of bot server.

I'm asking questions here because I can't find the exact cause. There was a problem with singing streaming even in similar situations before (use other youtube module).
Is there any additional solution that users should do?</div>

**Comment by tr1ckydev** [comment]
Is stream resource someway referenced somewhere else ?
Discord js/voice audio player says they destroy the resource as soon as it is finished playing
So maybe somewhere is the resource being piled up?
Correct me if i am wrong

**Comment by killer069** [comment]
> Is stream resource someway referenced somewhere else ?
> Discord js/voice audio player says they destroy the resource as soon as it is finished playing
> So maybe somewhere is the resource being piled up?
> Correct me if i am wrong

It is a issue of play-dl. It keeps on writing data even after stream doesn't want to. 

But in most cases, I think this should not be huge.
