### ISSUE TITLE
[=FEATURE=] Accept IDs for developer convenience

### ISSUE THREAD

**Issue by PapiOphidian** [play-dl/play-dl#47]
#### What problem are you trying to solve?

Passing only links to the lib is inconvenient and can easily lead to logical issues on the developer's end. The lib should instead accept both links and IDs and also offer a method to extract an ID from arbitrary string input similar to ytdl-core. Whether or not it parses an actual ID or what is intended to be a search result can be up to the developer and not this lib.

#### Describe the feature

```js
// example
require("play-dl").extractID(`https://www.youtube.com/watch?v=kJQP7kiw5Fk`) // kJQP7kiw5Fk
require("play-dl").extractID("kJQP7kiw5Fk") // kJQP7kiw5Fk
await require("play-dl").video_basic_info("kJQP7kiw5Fk") // Video {...
```

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by killer069** [comment]
@PapiOphidian 

Released 0.8.2 , Fixed all issues.
