### ISSUE TITLE
[=FEATURE=] Seek option

### ISSUE THREAD

**Issue by garder500** [play-dl/play-dl#70]
Add stream option to download from audio begin to download at defined start 

For example i wan't to download audio at the 7 second, i can with this option

**Comment by killer069** [comment]
> Add stream option to download from audio begin to download at defined start
> 
> For example i wan't to download audio at the 7 second, i can with this option

Seek feature is quite complicated. I will see if I can manage to do that.

**Comment by killer069** [comment]
Not Possible.

**Comment by bootleg-anonymous** [comment]
@killer069 I wanted to seek a song from yt/soundcloud, but I found [this](https://play-dl.github.io/classes/_internal_.SeekStream.html) on the documentation. Is it possible now? If so, can you give an example?

**Comment by bootleg-anonymous** [comment]
> @killer069 I wanted to seek a song from yt/soundcloud, but I found [this](https://play-dl.github.io/classes/_internal_.SeekStream.html) on the documentation. Is it possible now? If so, can you give an example?

Nvm, it worked like a charm. Thanks for making this repo possible

**Comment by masl** [comment]
Would you perhaps be so kind and share your code example with me? @bootleg-anonymous
