### ISSUE TITLE
[=BUG=] Playing music through youtube crashes

### ISSUE THREAD

**Issue by joelmagner** [play-dl/play-dl#83]
#### Following README example

 - Node.js version: 16.9.1
 - OS & version: Mac OS Big Sur

#### Actual behavior
Bot joins channel fine, then it crashes.

#### Expected behavior
It starts playing music.
 

#### Code to reproduce

```ts
  public startBot = async (): Promise<void> => {
    await this.login();
    this.client.on("ready", () => {
      console.log("Bot is running... ✅", this?.client?.user?.tag);
    });

    this.client.on("messageCreate", async (message: Message) => {
      if (!message.content.startsWith(this.prefix) || message.author.bot) {
        return;
      }

      const args = message.content.slice(this.prefix.length).split(/ +/);
      const cmd = args.shift()?.toLowerCase();
      if (cmd === "play") {
        if (!message?.member?.voice?.channel)
          await message.channel.send("Connect to a Voice Channel");
        else if (
          message.member?.voice.channel &&
          message.guild &&
          message.guild.id
        ) {
          const connection = joinVoiceChannel({
            channelId: message.member.voice.channel.id,
            guildId: message.guild.id,
            adapterCreator: message.guild.voiceAdapterCreator,
          });

          let yt_info = await play.search(args.join(" "), { limit: 1 });
          if (!yt_info[0].url) return;
          let stream = await play.stream(yt_info[0].url);
          let resource = createAudioResource(stream.stream, {
            inputType: stream.type,
          });
          let player = createAudioPlayer({
            behaviors: {
              noSubscriber: NoSubscriberBehavior.Play,
            },
          });
          player.play(resource);
          await message.channel.send(`Now playing **${args.join(" ")}**`);
          connection.subscribe(player);
        }
      } else if (cmd) command(this.client, message, cmd, args);
    });
  };
```

#### ScreenShots

node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by killer069** [comment]
This error will be fixed with 1.0 update. It has been patched in the pull request.

**Comment by joelmagner** [comment]
Great! Yeah I had a look at the PR just now. When is the new version being released?

**Comment by killer069** [comment]
> Great! Yeah I had a look at the PR just now. When is the new version being released?

Few days
