### ISSUE TITLE
[=ASK=] Lib types behaviour-change

### ISSUE THREAD

**Issue by joelmagner** [play-dl/play-dl#85]
#### What would you like to discuss?

The way to extract metadata does not seem quite optimal with the `.toJSON` property as it works today.

Eg.
```ts
const query = await play.search(args.join(" "), { limit: 1 });
if (query[0].url) {
   const metadata = query[0].toJSON; // Would preferably return an object with the keys on the object such as
   return { title: metadata.title, url: metadata.url};
   // would allow for destructuring like this:
   const { title, url } = query[0].toJSON;
}
```
Typescript cannot infer what the type of `play.search` will be. It suggests: `(Video | Channel | PlayList)[]` but i cannot set any of those types explicitly on `query` as they are not exported by the lib(?).

As far as I can tell there's no real way of getting to the properties that `.toJSON` returns when the object structure looks like this when logging what `.toJSON` returns.
```
[ Video { 
    title: "",
    url: "",
    ...
} ]
```
Any thoughts on possibly making changes to this?

#### Checklist

- [x] I have read the documentation.

**Comment by killer069** [comment]
Will see about this in few days.

**Comment by killer069** [comment]
@joelmagner 

They can be exported since I use export in classes.

Like `import { Video } from 'play-dl/YouTube/classes/Video'`
