### ISSUE TITLE
[=BUG=]  TypeError: player_response.streamingData.adaptiveFormats is not iterable (cannot read property undefined)

### ISSUE THREAD

**Issue by cjh980402** [play-dl/play-dl#86]
#### Describe the bug

 - Node.js version: 16.9.1
 - OS & version: ubuntu 20.04

#### Actual behavior

song url: https://www.youtube.com/watch?v=tL7HKKEoW1Y
Error is occured
```js
TypeError: player_response.streamingData.adaptiveFormats is not iterable (cannot read property undefined)
    at video_basic_info (/home/ubuntu/bot/node_modules/play-dl/dist/YouTube/utils/extractor.js:95:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.video_info (/home/ubuntu/bot/node_modules/play-dl/dist/YouTube/utils/extractor.js:120:16)
    at async stream (/home/ubuntu/bot/node_modules/play-dl/dist/YouTube/stream.js:27:16)
```

#### Expected behavior

 
No any error.

#### Code to reproduce

```js

```

#### ScreenShots

![image](https://user-images.githubusercontent.com/23624124/133927647-88ab92e5-da42-4ad1-bed0-7d2113f63400.png)
Some video doesn't have `player_response.streamingData.adaptiveFormats` like this.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Play-dl.

**Comment by cjh980402** [comment]
The error occurs before the high-resolution version is loaded.

**Comment by killer069** [comment]
I can't reproduce the error.

This url is working fine for me.

**Comment by cjh980402** [comment]
That's right coz now high resolution version is uploaded so that error can't occured.

**Comment by killer069** [comment]
Oh, then how can I solve this ??

**Comment by cjh980402** [comment]
I solved it like this
![Screenshot_20210920-130427_Samsung Internet](https://user-images.githubusercontent.com/23624124/133956026-87c763a2-e380-4542-afb8-2fb722008bc5.png)
