### ISSUE TITLE
[=BUG=] YouTube URL Verification

### ISSUE THREAD

**Issue by Shaynicide** [play-dl/play-dl#9]
https://youtube.com/watch?v=Xj8CAToRf1o

Currently, this doesn't pass the YouTube URL validation check and tells me it's not YouTube.

If I add "www." before YouTube it works, but I think it should be fine without it.

**Comment by killer069** [comment]
@Shaynicide Thanks for using play-dl

Errors have been fixed and tested on your given url.

**Comment by killer069** [comment]
Released v0.2.1

**Comment by killer069** [comment]
Issue still coming

**Comment by killer069** [comment]
Solved in v 0.4.0

**Comment by Junhaochia** [comment]
https://youtu.be/oF9yHO-UUws also doesn't work and throws
![image](https://user-images.githubusercontent.com/25685501/130475448-bad3b66e-6afa-4300-aff8-5af28a590949.png)

**Comment by killer069** [comment]
> https://youtu.be/oF9yHO-UUws also doesn't work and throws
> ![image](https://user-images.githubusercontent.com/25685501/130475448-bad3b66e-6afa-4300-aff8-5af28a590949.png)

Will be fixed in 0.5.0
