### ISSUE TITLE
[=FEATURE=] Customizable Stream Buffer sizes

### ISSUE THREAD

**Issue by PapiOphidian** [play-dl/play-dl#90]
#### What problem are you trying to solve?

10MB per stream is quite chonky depending on scale and is not actually the minimum required to operate depending on network stability and throughput. Being able to customize this depending on the user's circumstances could be huge in terms of memory efficiency.

#### Describe the feature
play_dl.stream(ID, undefined, { highWaterMark: 2_000_000 }); // 2MB is very reasonable on a stable and high throughput connection. A similar implementation could be achieved on other methods which make use of the Stream and LiveStream classes.

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by killer069** [comment]
First of all, highWaterMark is maximum amount of internal read buffers that it can hold.

![image](https://user-images.githubusercontent.com/65385476/134111692-19005cff-5242-43ef-a507-c91d3494c437.png)

So for example, if I have given a 10 MB highWaterMark, stream can have any size between 0 to 10 MB. 

Play-dl uses some optimizations to use as less memory it can use. So in practical use, stream would be having a size of 1 - 4 MB depending on audio.

If I am going to give this option to user, then it will create some issues with the optimizations that I have for discord.js bots.

So no planning to add this feature as of now.
